### ISSUE TITLE
Can't run due to missing modules

### ISSUE THREAD

**Issue by Theratherverydarkestlordever** [The-Dunadan/pumping-lemma-calculator#1]
I tried running your main.py as stated in the README.
Unfortunately, I receive an error message:

`Traceback (most recent call last):
  File "C:\...\Downloads\pumping-lemma-calculator-master\pumping-lemma-calculator-master\main.py", line 3, in <module>
    import parser
  File "C:\...\Downloads\pumping-lemma-calculator-master\pumping-lemma-calculator-master\parser.py", line 2, in <module>
    from conditionsParser import conditionsParser
ModuleNotFoundError: No module named 'conditionsParser'`

**Comment by stefanvodita** [comment]
Hi @Theratherverydarkestlordever! I haven't looked at this in a few years, but I think the missing piece is the ANTLR-generated lexer, listener, and parser. I should have covered this in the `README`, but it looks like ANTLR has some helpful [documentation](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md). You'll probably need to install ANTLR4 and then run something like `antlr4 -Dlanguage=Python conditions.g4`. I expect that to generate `conditionsLexer.py`, `conditionsListener.py`, `conditionsParser.py`. Hope that makes sense!

**Comment by Theratherverydarkestlordever** [comment]
Thank you for your quick reply.
I've already had antlr4 installed. I succesfully generated java-Code from conditions.g4 via `antlr4 conditions.g4`. Unfortunately, I could not achieve similar output fpr Python:
```
C:\Users\...\pumping-lemma-calculator-master\pumping-lemma-calculator-master>antlr4 -Dlanguage=Python conditions.g4

error(31):  ANTLR cannot generate Python code as of version 4.13.1
```

**Comment by stefanvodita** [comment]
The problem might be the antlr command. Have you tried being explicit about the Python version, like `antlr4 -Dlanguage=Python3 conditions.g4`?

**Comment by Theratherverydarkestlordever** [comment]
That helped, thanks.

**Comment by stefanvodita** [comment]
That's great! I'll update the README tomorrow. Let me know if you run into any other issues.
